/**
 * One-liners that pipe install scripts from the control plane.
 * Scripts are generated by GET /api/worker-downloads/install.sh and install.ps1.
 */

import { getBoardApiBase } from "./worker-client-hints";

function escapePosixSq(s: string): string {
  return s.replace(/'/g, "'\\''");
}

function escapePsSq(s: string): string {
  return s.replace(/'/g, "''");
}

export function stripTrailingSlashes(s: string): string {
  return s.replace(/\/+$/, "");
}

/** `curl … | bash` — macOS, Linux, WSL. */
export function buildPosixPipeInstallOneliner(apiBaseOverride?: string): string {
  const base = stripTrailingSlashes(apiBaseOverride ?? getBoardApiBase());
  return `curl -fsSL '${escapePosixSq(base)}/api/worker-downloads/install.sh' | bash`;
}

/** `irm … | iex` — Windows PowerShell. */
export function buildPowerShellPipeInstallOneliner(apiBaseOverride?: string): string {
  const base = stripTrailingSlashes(apiBaseOverride ?? getBoardApiBase());
  return `irm '${escapePsSq(base)}/api/worker-downloads/install.ps1' | iex`;
}

/** Pipe install then native `hive-worker pair` when `HIVE_PAIRING=1` (pairing window must be open on the board). */
export function buildPosixPipeInstallPairOneliner(apiBaseOverride: string | undefined, agentId: string): string {
  const base = stripTrailingSlashes(apiBaseOverride ?? getBoardApiBase());
  const id = agentId.trim();
  const q = id ? `?agentId=${encodeURIComponent(id)}` : "";
  return `curl -fsSL '${escapePosixSq(base)}/api/worker-downloads/install.sh${q}' | HIVE_PAIRING=1 bash`;
}

/** PowerShell: pipe install then `hive-worker.exe pair` when `HIVE_PAIRING=1`. */
export function buildPowerShellPipeInstallPairOneliner(apiBaseOverride: string | undefined, agentId: string): string {
  const base = stripTrailingSlashes(apiBaseOverride ?? getBoardApiBase());
  const id = agentId.trim();
  const q = id ? `?agentId=${encodeURIComponent(id)}` : "";
  return `$env:HIVE_PAIRING='1'; irm '${escapePsSq(base)}/api/worker-downloads/install.ps1${q}' | iex`;
}
