/**
 * Generate control-plane/.env.example from env-schema and ENV_VAR_DOCS.
 * Run from control-plane root: pnpm --filter @hive/shared generate:env-example
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { PARSED_ENV_KEYS, ENV_VAR_DOCS } from "../src/env-schema.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

function section(title: string): string {
  return `\n# ${title}\n`;
}

function lineForKey(key: string): string {
  const doc = ENV_VAR_DOCS[key];
  const desc = doc?.description ?? key;
  const defaultPart = doc?.default !== undefined ? ` (default: ${doc.default})` : "";
  const required = doc?.requiredWhen ? ` Required when ${doc.requiredWhen}.` : "";
  const comment = `# ${desc}${defaultPart}${required}`.trim();
  const defaultValue = doc?.default ?? "";
  const exampleValue = defaultValue ? `${key}=${defaultValue}` : `# ${key}=`;
  return `${comment}\n${exampleValue}`;
}

function groupKeys(keys: readonly string[]): Map<string, string[]> {
  const groups = new Map<string, string[]>();
  const push = (sectionName: string, key: string) => {
    if (!groups.has(sectionName)) groups.set(sectionName, []);
    groups.get(sectionName)!.push(key);
  };
  for (const key of keys) {
    if (key === "DATABASE_URL") push("Database (omit for embedded Postgres)", key);
    else if (key === "NODE_ENV") push("Server", key);
    else if (["HOST", "PORT", "SERVE_UI"].includes(key)) push("Server", key);
    else if (["HIVE_HOME", "HIVE_INSTANCE_ID", "HIVE_CONFIG", "HIVE_CONTEXT"].includes(key)) push("Hive paths", key);
    else if (
      [
        "HIVE_DEPLOYMENT_MODE",
        "HIVE_DEPLOYMENT_EXPOSURE",
        "HIVE_PUBLIC_URL",
        "HIVE_AUTH_PUBLIC_BASE_URL",
        "HIVE_AUTH_BASE_URL_MODE",
        "HIVE_ALLOWED_HOSTNAMES",
        "HIVE_UI_DEV_MIDDLEWARE",
        "HIVE_AUTH_DISABLE_SIGN_UP",
      ].includes(key)
    )
      push("Deployment and auth", key);
    else if (
      ["BETTER_AUTH_SECRET", "BETTER_AUTH_URL", "BETTER_AUTH_BASE_URL", "BETTER_AUTH_TRUSTED_ORIGINS", "HIVE_AGENT_JWT_SECRET"].includes(
        key,
      )
    )
      push("Auth (authenticated mode)", key);
    else if (
      [
        "HIVE_SECRETS_MASTER_KEY",
        "HIVE_SECRETS_MASTER_KEY_FILE",
        "HIVE_SECRETS_PROVIDER",
        "HIVE_SECRETS_STRICT_MODE",
      ].includes(key)
    )
      push("Secrets", key);
    else if (
      [
        "HIVE_STORAGE_PROVIDER",
        "HIVE_STORAGE_LOCAL_DIR",
        "HIVE_STORAGE_S3_BUCKET",
        "HIVE_STORAGE_S3_REGION",
        "HIVE_STORAGE_S3_ENDPOINT",
        "HIVE_STORAGE_S3_PREFIX",
        "HIVE_STORAGE_S3_FORCE_PATH_STYLE",
      ].includes(key)
    )
      push("Storage", key);
    else if (
      [
        "HIVE_DB_BACKUP_ENABLED",
        "HIVE_DB_BACKUP_INTERVAL_MINUTES",
        "HIVE_DB_BACKUP_RETENTION_DAYS",
        "HIVE_DB_BACKUP_DIR",
      ].includes(key)
    )
      push("DB backup", key);
    else if (["HIVE_CORS_ORIGINS", "HIVE_RATE_LIMIT_WINDOW_MS", "HIVE_RATE_LIMIT_MAX"].includes(key))
      push("CORS and rate limiting", key);
    else if (["HEARTBEAT_SCHEDULER_ENABLED", "HEARTBEAT_SCHEDULER_INTERVAL_MS"].includes(key)) push("Heartbeat", key);
    else if (["HIVE_ALLOWED_ATTACHMENT_TYPES", "HIVE_ATTACHMENT_MAX_BYTES"].includes(key)) push("Attachments", key);
    else if (
      [
        "HIVE_ENABLE_COMPANY_DELETION",
        "RUN_LOG_BASE_PATH",
        "HIVE_RELEASES_REPO",
        "HIVE_UPDATE_CHECK_DISABLED",
        "HIVE_WORKER_MANIFEST_URL",
        "HIVE_WORKER_RELEASES_REPO",
        "HIVE_WORKER_RELEASE_TAG",
        "HIVE_WORKER_ARTIFACT_BASE_URL",
        "HIVE_GITHUB_TOKEN",
        "HIVE_JOIN_ALLOWED_ADAPTER_TYPES",
        "HIVE_MANAGED_WORKER_URL_ALLOWLIST",
        "HIVE_LOG_DIR",
        "HIVE_LISTEN_HOST",
        "HIVE_LISTEN_PORT",
        "HIVE_API_URL",
        "HIVE_OPEN_ON_LISTEN",
        "HIVE_AGENT_JWT_TTL_SECONDS",
        "HIVE_AGENT_JWT_ISSUER",
        "HIVE_AGENT_JWT_AUDIENCE",
        "HIVE_SERVER_HOST",
        "HIVE_SERVER_PORT",
        "HIVE_E2E_PORT",
        "HIVE_E2E_SKIP_LLM",
        "HIVE_MIGRATION_PROMPT",
        "HIVE_MIGRATION_AUTO_APPLY",
        "HIVE_IN_WORKTREE",
        "CODEX_HOME",
        "CLAUDE_HOME",
      ].includes(key)
    )
      push("Optional", key);
    else push("Other", key);
  }
  return groups;
}

const sectionOrder = [
  "Database (omit for embedded Postgres)",
  "Server",
  "Hive paths",
  "Deployment and auth",
  "Auth (authenticated mode)",
  "Secrets",
  "Storage",
  "DB backup",
  "CORS and rate limiting",
  "Heartbeat",
  "Attachments",
  "Optional",
  "Other",
];

const groups = groupKeys(PARSED_ENV_KEYS);
const lines: string[] = [
  "# Generated by packages/shared/scripts/generate-env-example.ts from env-schema and ENV_VAR_DOCS.",
  "# Do not edit by hand; run: pnpm generate:env-example",
];
for (const sectionTitle of sectionOrder) {
  const keys = groups.get(sectionTitle);
  if (!keys?.length) continue;
  lines.push(section(sectionTitle));
  for (const key of keys) {
    lines.push(lineForKey(key));
    lines.push("");
  }
}
const out = lines.join("\n").trimEnd() + "\n";
const outPath = join(__dirname, "..", "..", "..", ".env.example");
writeFileSync(outPath, out, "utf8");
console.log("Wrote", outPath);
